---
- name: Prepare server with required tools and configurations
  hosts: multi-env
  vars:

    ansible_user: "{{ lookup('env', 'USER') }}"  # Uses the current user if not specified
  vars_files:
    - multi_vars.yml

  roles:
    - role: multi-env-simulation

