---
# tasks file for nvidia-driver-installer
- name: Copy NVIDIA driver installation script to target server
  copy:
        src: nvidia_driver_install.sh  # Local path to the script
        dest: /tmp/nvidia_driver_install.sh
        mode: '0755'  # Sets execute permissions

- name: Run NVIDIA driver installation script
  command: /tmp/nvidia_driver_install.sh
  args:
        chdir: /tmp
  register: script_output
  ignore_errors: false  # Fail the playbook if installation fails

- name: Display script output
  debug:
        msg: "{{ script_output.stdout }}"

- name: Force reboot the server after successful installation
  reboot:
  when: script_output.rc == 0  # Reboot only if script exit code is 0
  become: true

- name: Wait for server to come back online after reboot
  wait_for_connection:
        timeout: 300
  when: script_output.rc == 0

